config/routes.rb
Quipper::Application.routes.draw do
  resources :tasks do
    get 'done', on: :collection
    get 'pending', on: :collection
    get 'expired', on: :collection
  end

  root :to => "tasks#index"
end

app/models/task.rb
# A task to be managed
class Task < ActiveRecord::Base
  attr_accessible :deadline, :done, :name

  validates_presence_of :name
  validates_length_of :name, maximum: 32

  scope :pending, where('deadline >= ? AND done = ?', Time.now.utc.to_date, false)
  scope :done, where(done: true)
  scope :expired, where('deadline < ? AND done = ?', Time.now.utc.to_date, false)

  # Returns the task status
  # @return ['expired', nil] a constant 'expired' otherwise nil
  def status
    'expired' if deadline && self.expired?
  end

  # Computes if the task deadline has passed
  # @return [Boolean]
  def expired?
    self.deadline.try(:<, Time.now.utc.to_date) && !self.done?
  end

  # Marks the task as completed
  # @return [nil]
  def mark_as_done
    self.done = true
    save
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/tasks_controller.rb
# Creates, edits, displays and deletes tasks.
# @see Task
class TasksController < ApplicationController

  before_filter :initialize_task, only: [:index, :done, :pending, :expired]
  before_filter :apply_filters, only: [:index, :done, :pending, :expired]

  # Shows all tasks
  def index
    @title = :all_tasks
  end

  # Edits one task
  def edit
    @task = Task.find(params[:id])
    session[:return_to] = request.referer
  end

  # Creates a new task
  def create
    @task = Task.new(params[:task])

    respond_to do |format|
      if @task.save
        format.html { redirect_to tasks_path, notice: t(:task_created) }
      else
        apply_filters
        format.html { render action: "index" }
      end
    end
  end

  # Updates a task's attributes
  def update
    @task = Task.find(params[:id])
    if @task.update_attributes(params[:task])
      respond_to do |format|
        format.js
        format.html { redirect_to session[:return_to], notice: t(:task_updated) }
      end
    else
      render action: "edit"
    end
  end

  # Destroys a task
  def destroy
    @task = Task.find(params[:id])
    @task.destroy

    respond_to do |format|
      format.html { redirect_to tasks_url }
    end
  end

  # Returns the list of tasks that have been done
  def done
    @title = :tasks_done
    @tasks = @tasks.done

    render 'index'
  end

  # Returns the list of pending tasks
  def pending
    @title = :pending_tasks
    @tasks = @tasks.pending

    render 'index'
  end

  # Returns the list of expired tasks
  def expired
    @title = :expired_tasks
    @tasks = @tasks.expired

    render 'index'
  end

  private
  # Instantiates a new task
  def initialize_task
    @task = Task.new
  end

  # Searches tasks by name, and the result is paginated and sorted by deadline
  def apply_filters
    params[:q] = params[:q] ? params[:q].reverse_merge({ s: 'deadline asc' }) : { s: 'deadline asc' }
    @search = Task.search(params[:q])
    @tasks = @search.result.paginate(:page => params[:page], :per_page => 8)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/tasks_helper.rb
module TasksHelper

  # Returns a css style based on the tasks status
  # @param [Task] task to display
  # @return ['expired', nil]
  # @see Task#status
  def task_row_class(task)
    task.status
  end

  # Returns a css style based on a filter name
  # @param ['today', 'week', 'month'] name of a date filter 
  # @return ['active', nil] 'active' if the filter is active
  def is_active_date?(filter)
    'active' if params.has_value?(filter.to_s)
  end
  
  # Returns a css style when there is no active filter
  # @return ['active', nil] 'active' if there is no active filter
  def is_active_any_date?
    'active' unless params.has_key?('f')
  end

  # Returns the correct url path for a given filter name
  # @param ['today', 'week', 'month'] name of a date filter 
  # @return [Hash] a hash that represents a route tailored for a given filter
  #   * :controller [String] the name of the controller: 'tasks'
  #   * :action ['index', 'pending', 'done', 'expired'] the action requested on the controller 'tasks'
  #   * :name_cont [String] the search string that is part of the name of a task
  #   * :deadline_gteq [String] for search, the lower limit of the valid dateline range
  #   * :deadline_lteq [String] for search, the upper limit of the valid dateline rangeyy
  #   * :s ['deadline desc', 'deadline asc'] the sort_by field and asc/desc selector 
  #   * :f ['today', 'week', 'month'] the name of the date filter
  def date_filter_path(filter)
    if params[:q]
      case filter
        when :today
          params.merge(q: {deadline_eq: Date.today, name_cont: params[:q][:name_cont], s: params[:q][:s]}, 
                       f: :today).except(:page)
        when :week
          params.merge(q: {deadline_gteq: Date.today.beginning_of_week, deadline_lteq: Date.today.end_of_week, 
                           name_cont: params[:q][:name_cont], s: params[:q][:s]}, f: :week).except(:page)
        when :month
          params.merge(q: {deadline_gteq: Date.today.beginning_of_month, deadline_lteq: Date.today.end_of_month, 
                           name_cont: params[:q][:name_cont], s: params[:q][:s]}, f: :month).except(:page)
        when :any
          params[:q].except(:deadline_gteq, :deadline_lteq, :page, :name_cont, :s)
        else
          nil
      end
    end
  end
end

app/views/layouts/_navigation.html.haml
.navbar-inner
  .container
    .btn-navbar-wrapper
      %a.btn.btn-navbar{"data-target" => ".nav-collapse", "data-toggle" => "collapse", 'title' => 'Menu'}
        %span.icon-bar
        %span.icon-bar
        %span.icon-bar
    .nav-collapse
      %ul.nav.primary_nav
        %li= link_to t(:all), tasks_path
        %li= link_to t(:pending), pending_tasks_path
        %li= link_to t(:done), done_tasks_path
        %li= link_to t(:expired), expired_tasks_path

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:name => "viewport", :content => "width=device-width, initial-scale=1"}
    %title= content_for?(:title) ? yield(:title) : "Quipper"
    = stylesheet_link_tag    "application", :media => "all"
    = javascript_include_tag "application"
    = csrf_meta_tags
  %body
    %header.container
      = link_to image_tag('quipper_logo.png', alt: 'Quipper'), root_path
    .navbar
      = render 'layouts/navigation'
    #main.container
      .row
        .span9
          - if flash[:notice]
            .alert.alert-success
              %button.close{'data-dismiss' => 'alert'} ×
              = flash[:notice]
          = yield
        .span3
          .heading
            %h2= t(:quipper_todo)
          %p= t(:quipper_explanation)

app/views/tasks/_form.html.haml
= simple_form_for(@task, html: { class: 'form-horizontal' }) do |f|
  = f.error_notification
  .form-inputs
    = f.input :name
    = f.input :deadline, as: :string, input_html: { class: 'datepicker' }
  .form-actions
    = f.button :submit, class: 'btn btn-primary'
    - if @task.new_record?
      = link_to t(:cancel), '#', onClick: 'return false', class: 'btn', 'data-toggle' => "collapse",
        'data-target'=>"#new_task_container"
    - else
      = link_to t(:back), :back, class: 'btn'

app/views/tasks/_new.html.haml
.heading
  %h1= t(:new_task)
= render 'form'

app/views/tasks/edit.html.haml
.heading
  %h1= t(:edit_task)
= render 'form'

app/views/tasks/index.html.haml
- content_for :title, "Quipper - #{t(@title)}"
#new_task_container.collapse
  = render 'new'
.heading
  %h1.floating= t(@title)
  = link_to '#', onClick: 'return false', id: 'new-task-link', 'data-toggle' => "collapse",
    'data-target'=>"#new_task_container", class: 'btn btn-success' do
    %i.icon-pencil.icon-white
    = t(:new_task)
.filter
  .btn-group{"data-toggle" => "buttons-radio"}
    = link_to t(:today), date_filter_path(:today), class: "btn #{is_active_date?(:today)}"
    = link_to t(:week), date_filter_path(:week), class: "btn #{is_active_date?(:week)}"
    = link_to t(:month), date_filter_path(:month), class: "btn #{is_active_date?(:month)}"
    = link_to t(:any), date_filter_path(:any), class: "btn #{is_active_any_date?}"
  = search_form_for @search, html: {class: 'form-search'} do |f|
    = f.text_field :name_cont, class: '.input-medium search-query'
    = f.submit t(:search), class: 'btn', id: 'search-btn'
%table.table
  %thead
    %tr
      %th.visible-phone
      %th= t(:mark_done)
      %th= sort_link @search, :name, t(:task), {page: params[:page], f: params[:f]}, {id: 'sort_name'}
      %th= sort_link @search, :deadline, t(:deadline), {page: params[:page], f: params[:f]}, {id: 'sort_deadline'}
      %th.hidden-phone2= sort_link @search, :created_at, t(:created_at), {page: params[:page], f: params[:f]}, {id: 'sort_created_at'}
      %th.hidden-phone= t(:action)
      %th.visible-phone
  %tbody
    - @tasks.each do |task|
      %tr{ class: "#{task_row_class(task)}"}
        = hidden_field_tag :id, task.id, id: "id_#{task.id}"
        %td.visible-phone
          = link_to edit_task_path(task), class: 'btn btn-primary btn-mini', title: t(:edit) do
            %i.icon-edit.icon-white
        %td= check_box_tag 'done', nil, task.done, id: "checkbox_#{task.id}", status_url: task_path(task), disabled: task.expired?
        %td.name= task.name
        %td= task.deadline.try(:strftime, '%d %B %Y')
        %td.hidden-phone2= task.created_at.strftime('%d %B %Y')
        %td.hidden-phone
          = link_to edit_task_path(task), class: 'btn btn-primary btn-mini', title: t(:edit) do
            %i.icon-edit.icon-white
            %span.link-name.hidden-phone= t(:edit)
          = link_to task, confirm: t(:delete_question), method: :delete, class: 'btn btn-danger btn-mini', title: t(:delete) do
            %i.icon-trash.icon-white
            %span.hidden-phone.link-name= t(:delete)
        %td.visible-phone
          = link_to task, confirm: t(:delete_question), method: :delete, class: 'btn btn-danger btn-mini', title: t(:delete) do
            %i.icon-trash.icon-white

= will_paginate @tasks, class: 'pagination hidden-phone'
= will_paginate @tasks, page_links: false, class: 'pagination visible-phone'

app/views/tasks/update.js.erb
window.location.href = '<%= request.referer %>';